### PR TITLE
Added additional country (Vietnam)

### PR DESCRIPTION
**Pull request by sroemer**
Hi,
I added Vietnam as an additional country to the mt.pl skript. So far elevation data is missing, but except of this the map seems to be working fine. 

As already mentioned in the [comments](https://github.com/freizeitkarte/fzk-mde-garmin/pull/3) to another pull request I also think that there is missing some kind of documention regarding the creation of elevation data. Maybe it also would be helpful to get an option for overriding the 'elevationurlbasepath', since this would simplify testing without having access to the Freizeitkarte-OSM.de server. What is your opinion on that? I would be willing to work on that in the next days.

Kind regards,
  Stefan.

### CODE REVIEW

**Comment by keenonkites** [comment]
I'd like to merge the two commits a0fae57 and 9ce4034. Do you know how to perform this ? I don't know git good enough to perform that without 'risks' or help...
;-)

**Comment by sroemer** [comment]
I think it was not good from my side to have all those in one single pull request, but with it being that way I think the easist way to merge would have been merging the whole pull request before doing additional changes (because those generated conflicts) on the branch. I think in that case merging would have been possible with just one click here in Github (maybe a little more than that).

Even now you can proceed by using git cherrypick  for the commits you want to use. I searched the web and found those [instructions](http://mispdev.blogspot.de/2013/02/github-cherry-picking-commits-from-pull.html). The important part is the last part "How to do cherry picking".

At least I think there is not a huge risk as long as you are working on your local copy and do only push to the server in case you got the things right.

**Comment by sroemer** [comment]
Related to my first comment please forget about what I said about "overriding the 'elevationurlbasepath'". I later reallized that I easily can use the script and just copy my locally created elevation data file into the right directory, so I think that would not be very helpful.

Since that time I also generated some elevation data by using following commands: 

```
phyghtmap -j 4 -s 20 -c 500,100 --max-nodes-per-tile=0 --max-nodes-per-way=0 --start-node-id=10000000000 --start-way-id=10000000000 --polygon=vietnam.poly --source=view3 --pbf -o Hoehendaten_Freizeitkarte_VNM_20
phyghtmap -j 4 -s 10 -c 200,100 --max-nodes-per-tile=0 --max-nodes-per-way=0 --start-node-id=10000000000 --start-way-id=10000000000 --polygon=vietnam.poly --source=view3 --pbf -o Hoehendaten_Freizeitkarte_VNM_10
```

**Comment by keenonkites** [comment]
Cherrypicking: read about it.... looks like I'll get bit deeper on it, thought that this should be the soltution, but never used it before.

Elevation: the 'internal' scripts we use is in the elevation subdir of https://github.com/freizeitkarte/fzk-utils 

As soon as I have done the cherrypicking I'll see if I can build also the elevation data for the missing country.

**Comment by keenonkites** [comment]
cherry picking done, 'sweet' cherries picked out.. ;-)
Vietnam elevation data is under construction... I assume it won't eat too much space, hopefully

**Comment by sroemer** [comment]
Seems I did not dig deep enough for finding those scripts :)

Regarding the size I have no idea how this compares to other countries, but since Vietnam has a lot of quite hilly regions it will not be one of the smallest I guess.

Anyway, thanks a lot for adding it to the script. I am looking forward to use the map on my next trip :)

**Comment by keenonkites** [comment]
Elevation data for VNM is ready...  you're welcome

**Comment by sroemer** [comment]
Thanks again. I rebuilt my map and everything worked well.
--> Closing this now.

**Pull request closed without merging**
