### PR TITLE
Update mkgmap.jar

### PR DESCRIPTION
**Pull request by enginefeeder101**
Version bump for mkgmap.jar to r4899

See [changelog](https://www.mkgmap.org.uk/websvn/log.php?repname=mkgmap&path=%2F&isdir=1&sr=4899&er=4224&max=1000&search=&all=1) of mkgmap for updates.

### CODE REVIEW

**Comment by keenonkites** [comment]
Thanks for the pull request.
Is there any specific reason for this update ? Special feature you want or bug in mkgmap that's fixed ?
Thanks for explaining.
Cheers Patrik

**Comment by enginefeeder101** [comment]
Entschuldigung, I should have explained a bit more.
I use this toolchain to generate maps for specific cut-regions, super useful when close to a border of provided maps. As routing on a single map is so much easier. Thank you for this tool! 😀
However, mkgmap r4223 (dd 2018-08-13) and the [OpenFietsMap styles](https://github.com/ligfietser/mkgmap-style-sheets) generate errors, and no map is build on running `./mt.pl build`:
```
java -Xmx6000M -Dfile.encoding=UTF-8 -jar /anonymisiert/Freizeitkarte-Entwicklung/tools/mkgmap/mkgmap.jar ↵
  --max-jobs -c CustomArea.cfg --check-styles
Found one style in /anonymisiert/Freizeitkarte-Entwicklung/work/CustomArea_en/style/ofm
Error in style: Error: (points:2): Expecting ), instead saw boundary
could not open style ofm
finished check-styles
Error in style: Error: (points:2): Expecting ), instead saw boundary
Error in style: Error: (points:2): Expecting ), instead saw boundary
Error in style: Error: (points:2): Expecting ), instead saw boundary
Error in style: Error: (points:2): Expecting ), instead saw boundary
Error in style: Error: (points:2): Expecting ), instead saw boundary
Error in style: Error: (points:2): Expecting ), instead saw boundary
Error in style: Error: (points:2): Expecting ), instead saw boundary
Error in style: Error: (points:2): Expecting ), instead saw boundary
Error in style: Error: (points:2): Expecting ), instead saw boundary
Error in style: Error: (points:2): Expecting ), instead saw boundary
Could not open style
Number of ExitExceptions: 1
Total time taken: 428 ms
Warning: system(java -Xmx6000M -Dfile.encoding=UTF-8 -jar /anonymisiert/Freizeitkarte-Entwicklung/tools ↵
  mkgmap/mkgmap.jar  --max-jobs -c CustomArea.cfg --check-styles) failed: 256
Child exited with value 1
Elapsed, System-RC, Action-RC: 1, 256, 1
ERROR:
  Creating the map CustomArea with mkgmap failed.
```
Bumped mkgmap to r4899 (dd 2022-04-08) and the errors were gone, and a nice map was built. Probably ligfietser is using a feature that was introduces somewhere the past 4 years. But I haven't investigated that.
To check that the Freizeitkarte style worked with this mkgmap version I also build a couple maps with the normal fzk style and no obvious regression there.

If you do not want to merge, that is fine. But it might be useful to others as well.

**Comment by keenonkites** [comment]
I will make an session to update some of the tools in the chain in the near future, also including mkgmap for sure.
At the moment I will not pull this request, but leave it open for the moment... as a reminder... hope that's ok for you.
Thanks for the additional explanations.
Cheers Patrik

**Comment by keenonkites** [comment]
I've updated mkgmap and other used tools to up2date versions in a feature branch and will soon merge it to develop.
Therefore I close this pull request.
Cheers Patrik

**Pull request closed without merging**
